apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: demo-voting-app-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: demo-voting-app-pod
  template:
    metadata:
          name: redis-pod
          labels:
                name: redis-pod
                app: demo-voting-app-pod
    spec:
     containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379